# Form implementation generated from reading ui file 'picard-plugin-dump-loaded-album/options_dump_loaded_album.ui'
#
# Created by: PyQt6 UI code generator 6.6.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets  # noqa: F401


class Ui_DumpLoadedAlbumOptionsPage(object):
    def setupUi(self, DumpLoadedAlbumOptionsPage):
        DumpLoadedAlbumOptionsPage.setObjectName("DumpLoadedAlbumOptionsPage")
        DumpLoadedAlbumOptionsPage.resize(561, 571)
        DumpLoadedAlbumOptionsPage.setMinimumSize(QtCore.QSize(100, 0))
        self.verticalLayout = QtWidgets.QVBoxLayout(DumpLoadedAlbumOptionsPage)
        self.verticalLayout.setObjectName("verticalLayout")
        self.page_title = QtWidgets.QLabel(parent=DumpLoadedAlbumOptionsPage)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        self.page_title.setFont(font)
        self.page_title.setObjectName("page_title")
        self.verticalLayout.addWidget(self.page_title)
        self.format_description = QtWidgets.QLabel(parent=DumpLoadedAlbumOptionsPage)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.format_description.sizePolicy().hasHeightForWidth())
        self.format_description.setSizePolicy(sizePolicy)
        self.format_description.setTextFormat(QtCore.Qt.TextFormat.MarkdownText)
        self.format_description.setWordWrap(True)
        self.format_description.setObjectName("format_description")
        self.verticalLayout.addWidget(self.format_description)
        spacerItem = QtWidgets.QSpacerItem(20, 6, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Fixed)
        self.verticalLayout.addItem(spacerItem)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setContentsMargins(-1, 0, -1, -1)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.target_dir_label = QtWidgets.QLabel(parent=DumpLoadedAlbumOptionsPage)
        self.target_dir_label.setObjectName("target_dir_label")
        self.horizontalLayout.addWidget(self.target_dir_label)
        self.target_dir = QtWidgets.QLineEdit(parent=DumpLoadedAlbumOptionsPage)
        self.target_dir.setText("")
        self.target_dir.setReadOnly(True)
        self.target_dir.setObjectName("target_dir")
        self.horizontalLayout.addWidget(self.target_dir)
        self.b_select_target_dir = QtWidgets.QToolButton(parent=DumpLoadedAlbumOptionsPage)
        self.b_select_target_dir.setText("...")
        self.b_select_target_dir.setObjectName("b_select_target_dir")
        self.horizontalLayout.addWidget(self.b_select_target_dir)
        self.verticalLayout.addLayout(self.horizontalLayout)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout.addItem(spacerItem1)

        self.retranslateUi(DumpLoadedAlbumOptionsPage)
        QtCore.QMetaObject.connectSlotsByName(DumpLoadedAlbumOptionsPage)
        DumpLoadedAlbumOptionsPage.setTabOrder(self.target_dir, self.b_select_target_dir)

    def retranslateUi(self, DumpLoadedAlbumOptionsPage):
        _translate = QtCore.QCoreApplication.translate
        DumpLoadedAlbumOptionsPage.setWindowTitle(_translate("DumpLoadedAlbumOptionsPage", "Dump Loaded Album Options"))
        self.page_title.setText(_translate("DumpLoadedAlbumOptionsPage", "page.title"))
        self.format_description.setText(_translate("DumpLoadedAlbumOptionsPage", "page.description"))
        self.target_dir_label.setText(_translate("DumpLoadedAlbumOptionsPage", "label.target_dir"))
        self.b_select_target_dir.setToolTip(_translate("DumpLoadedAlbumOptionsPage", "tooltip.button.select_target_dir"))
